HEAT_LOSS_METHOD_MEAN_TEMPERATURE = 'mean_temperature'
HEAT_LOSS_METHOD_LEGACY_MAINT_TEMPERATURE = 'legacy_maint_temperature'
HEAT_LOSS_METHOD_STANDARD_TABLE = 'standard_table'
HEAT_LOSS_METHOD_INTEGRATED_KT = 'integrated_kT'
HEAT_LOSS_METHOD_FIXED_PROJECT_BASIS = 'fixed_project_basis'

DEFAULT_HEAT_LOSS_METHOD = HEAT_LOSS_METHOD_MEAN_TEMPERATURE

HEAT_LOSS_METHOD_CHOICES = [
    (HEAT_LOSS_METHOD_MEAN_TEMPERATURE, 'Mean insulation temperature (recommended)'),
    (HEAT_LOSS_METHOD_LEGACY_MAINT_TEMPERATURE, 'Legacy maintain temperature'),
    (HEAT_LOSS_METHOD_STANDARD_TABLE, 'Standard/vendor table (placeholder)'),
    (HEAT_LOSS_METHOD_INTEGRATED_KT, 'Integrated k(T) (placeholder)'),
    (HEAT_LOSS_METHOD_FIXED_PROJECT_BASIS, 'Fixed project basis (placeholder)'),
]

IMPLEMENTED_HEAT_LOSS_METHODS = {
    HEAT_LOSS_METHOD_MEAN_TEMPERATURE,
    HEAT_LOSS_METHOD_LEGACY_MAINT_TEMPERATURE,
}

PLACEHOLDER_HEAT_LOSS_METHODS = {
    HEAT_LOSS_METHOD_STANDARD_TABLE,
    HEAT_LOSS_METHOD_INTEGRATED_KT,
    HEAT_LOSS_METHOD_FIXED_PROJECT_BASIS,
}

HEAT_LOSS_METHOD_LABELS = dict(HEAT_LOSS_METHOD_CHOICES)


def normalize_heat_loss_method(method):
    method = method or DEFAULT_HEAT_LOSS_METHOD
    if method in HEAT_LOSS_METHOD_LABELS:
        return method
    return DEFAULT_HEAT_LOSS_METHOD
