# Generated by Django 4.2.16 on 2024-12-26 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatTracingInput',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('proj_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('line_id', models.CharField(max_length=100)),
                ('pid_no', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, max_length=10, null=True)),
                ('train', models.CharField(blank=True, max_length=10, null=True)),
                ('service_type', models.CharField(max_length=20)),
                ('line_size', models.DecimalField(decimal_places=4, max_digits=10)),
                ('line_length', models.DecimalField(decimal_places=4, max_digits=10)),
                ('xlid', models.PositiveIntegerField(blank=True, null=True)),
                ('valve_qty', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('flange_qty', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('support_qty', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('pipe_mat_class', models.CharField(blank=True, max_length=50, null=True)),
                ('ins_mat_type', models.CharField(max_length=20)),
                ('insul_thick', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maint_temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('oper_temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('design_temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('emergency_supply', models.BooleanField(default=False)),
                ('discipline', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Heat Tracing Input',
                'verbose_name_plural': 'Heat Tracing Inputs',
            },
        ),
        migrations.CreateModel(
            name='ProjectData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('proj_id', models.CharField(choices=[('p1', 'P001'), ('p2', 'P002')], default='p1', max_length=20, unique=True, verbose_name='Project ID')),
                ('min_amb_t', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_amb_t', models.DecimalField(decimal_places=2, max_digits=5)),
                ('startup_t', models.DecimalField(decimal_places=2, max_digits=5)),
                ('area_class', models.CharField(max_length=20)),
                ('temp_class', models.CharField(max_length=20)),
                ('voltage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_cb_size', models.IntegerField(choices=[(0, 10), (1, 16), (2, 20), (3, 25), (4, 32), (5, 40)], default=5)),
                ('restrict_cb_current', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vendor', models.CharField(choices=[('THR', 'Thermon'), ('CHR', 'Chromalox'), ('nVN', 'nVent'), ('SST', 'SST'), ('KRZ', 'KRUS-Zapad')], default='THR', max_length=30)),
                ('tracer_family', models.CharField(max_length=30)),
                ('spiral_wrap_allowed', models.CharField(choices=[('Yes', 'Allowed'), ('No', 'Not Allowed')], default='No', max_length=30)),
                ('spiral_factor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valve_factor', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('flange_factor', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('support_factor', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('margin_on_tracer_lengths', models.DecimalField(decimal_places=2, max_digits=5)),
                ('voltage_var_factor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('res_tol', models.DecimalField(decimal_places=2, max_digits=5)),
                ('termination_margin', models.DecimalField(decimal_places=2, max_digits=8)),
                ('heat_loss_sf', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rtd_thrm', models.CharField(choices=[('RI', 'RTD-Inline'), ('RO', 'RTD-Offline'), ('TI', 'Thermostat-Inline'), ('TO', 'Thermostat-Offline')], default='TI', max_length=50)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=8)),
                ('req_local_isolator', models.CharField(max_length=30)),
                ('caution_label_interval', models.DecimalField(decimal_places=2, max_digits=5)),
                ('k_factor_ccons', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('isolator_location', models.CharField(choices=[('I', 'Case I'), ('II', 'Case II'), ('III', 'Case III'), ('IV', 'Case IV')], default='II', max_length=20)),
                ('ckt_ln', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loop_ln', models.DecimalField(decimal_places=2, max_digits=5)),
                ('acc_power_density', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('tracer_temp_factor', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('alpha_for_res', models.DecimalField(decimal_places=4, default=1, max_digits=6)),
                ('allowablevdrop', models.DecimalField(decimal_places=2, max_digits=5)),
                ('udf1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('udf2', models.CharField(blank=True, max_length=30, null=True)),
                ('udf3', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(auto_now_add=True)),
                ('lockout', models.BooleanField(default=False)),
                ('cooldown_expires', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
