# Generated by Django 5.2.13 on 2026-04-18 02:32

import django.db.models.deletion
from django.db import migrations, models


def clear_legacy_derived_results(apps, schema_editor):
    model_names = [
        'PowerDistributionBranch',
        'PowerDistribution',
        'AlternateTracer',
        'SelectedTracer',
        'HeatLoss',
        'BOQ',
        'ProcessLineCalculation',
    ]
    for model_name in model_names:
        apps.get_model('eht', model_name).objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternatetracer',
            options={'ordering': ['line', 'option_rank']},
        ),
        migrations.AlterModelOptions(
            name='boq',
            options={'ordering': ['scope', 'line', 'item_code']},
        ),
        migrations.AlterModelOptions(
            name='heatloss',
            options={'ordering': ['line']},
        ),
        migrations.AlterModelOptions(
            name='powerdistribution',
            options={'ordering': ['line']},
        ),
        migrations.AlterModelOptions(
            name='powerdistributionbranch',
            options={'ordering': ['distribution', 'branch_index']},
        ),
        migrations.AlterModelOptions(
            name='processlinecalculation',
            options={'ordering': ['line']},
        ),
        migrations.AlterModelOptions(
            name='selectedtracer',
            options={'ordering': ['line']},
        ),
        migrations.AlterField(
            model_name='alternatetracer',
            name='v_uid',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='alternatetracer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='alternatetracer',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternate_tracer_results', to='eht.heattracinginput'),
        ),
        migrations.AddField(
            model_name='alternatetracer',
            name='option_rank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boq',
            name='uid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='boq',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='boq',
            name='item_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='boq',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boq_items', to='eht.heattracinginput'),
        ),
        migrations.AddField(
            model_name='boq',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boq_items', to='eht.projectdata', to_field='proj_id'),
        ),
        migrations.AddField(
            model_name='boq',
            name='scope',
            field=models.CharField(choices=[('line', 'Line'), ('consolidated', 'Consolidated')], default='line', max_length=20),
        ),
        migrations.AddField(
            model_name='heatloss',
            name='line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heat_loss_result', to='eht.heattracinginput'),
        ),
        migrations.AddField(
            model_name='powerdistribution',
            name='line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='power_distribution_result', to='eht.heattracinginput'),
        ),
        migrations.AddField(
            model_name='powerdistributionbranch',
            name='branch_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processlinecalculation',
            name='breaker_size',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='processlinecalculation',
            name='line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_line_calculation', to='eht.heattracinginput'),
        ),
        migrations.AddField(
            model_name='processlinecalculation',
            name='pipe_size_mm',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='processlinecalculation',
            name='total_circuits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processlinecalculation',
            name='total_tracer_length',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='selectedtracer',
            name='v_uid',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='selectedtracer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='selectedtracer',
            name='line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_tracer_result', to='eht.heattracinginput'),
        ),
        migrations.AlterField(
            model_name='boq',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boq',
            name='item_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='boq',
            name='unit',
            field=models.CharField(blank=True, default='EA', max_length=50),
        ),
        migrations.AlterField(
            model_name='powerdistributionbranch',
            name='cable_length_jb_to_jb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='powerdistributionbranch',
            name='tagged_components',
            field=models.TextField(default='{}'),
        ),
        migrations.AddIndex(
            model_name='boq',
            index=models.Index(fields=['project', 'scope'], name='eht_boq_project_9c2810_idx'),
        ),
        migrations.AddIndex(
            model_name='boq',
            index=models.Index(fields=['line', 'scope'], name='eht_boq_line_id_d6e2e2_idx'),
        ),
        migrations.AddIndex(
            model_name='boq',
            index=models.Index(fields=['item_code'], name='eht_boq_item_co_e2b754_idx'),
        ),
        migrations.AddConstraint(
            model_name='alternatetracer',
            constraint=models.UniqueConstraint(fields=('line', 'option_rank'), name='unique_alternate_tracer_rank_per_line'),
        ),
        migrations.AddConstraint(
            model_name='powerdistributionbranch',
            constraint=models.UniqueConstraint(fields=('distribution', 'branch_index'), name='unique_branch_index_per_distribution'),
        ),
        migrations.RunPython(clear_legacy_derived_results, migrations.RunPython.noop),
    ]
