# Generated by Django 4.2.16 on 2024-12-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0002_alter_heattracinginput_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heattracinginput',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=20),
        ),
    ]
