# Generated by Django 5.2.13 on 2026-04-18 21:07

from django.db import migrations, models


def normalize_project_setup_rows(apps, schema_editor):
    ProjectData = apps.get_model('eht', 'ProjectData')
    valid_max_cb_sizes = {10, 16, 20, 25, 32, 40}
    valid_tracer_families = {'Self Regulating', 'Constant Wattage', 'MI'}
    valid_local_isolator_flags = {'required', 'not_required'}
    valid_isolator_locations = {'bothSides', 'outgoingOnly', 'incomingOnly', 'noIsolator'}

    for project in ProjectData.objects.all():
        project.proj_id = (project.proj_id or '').strip()

        if project.max_cb_size not in valid_max_cb_sizes:
            project.max_cb_size = 10

        if project.tracer_family not in valid_tracer_families:
            project.tracer_family = 'Self Regulating'

        if project.req_local_isolator not in valid_local_isolator_flags:
            project.req_local_isolator = 'required'

        if project.isolator_location not in valid_isolator_locations:
            project.isolator_location = 'noIsolator'

        project.save(update_fields=[
            'proj_id',
            'max_cb_size',
            'tracer_family',
            'req_local_isolator',
            'isolator_location',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0002_alter_alternatetracer_options_alter_boq_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdata',
            name='isolator_location',
            field=models.CharField(choices=[('bothSides', 'Both Sides'), ('outgoingOnly', 'Outgoing Only'), ('incomingOnly', 'Incoming Only'), ('noIsolator', 'No Isolator')], default='noIsolator', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='max_cb_size',
            field=models.IntegerField(choices=[(10, 10), (16, 16), (20, 20), (25, 25), (32, 32), (40, 40)], default=10),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='proj_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Project ID'),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='req_local_isolator',
            field=models.CharField(choices=[('required', 'Required'), ('not_required', 'Not Required')], default='required', max_length=30),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='tracer_family',
            field=models.CharField(choices=[('Self Regulating', 'Self Regulating'), ('Constant Wattage', 'Constant Wattage'), ('MI', 'MI')], default='Self Regulating', max_length=30),
        ),
        migrations.RunPython(normalize_project_setup_rows, migrations.RunPython.noop),
    ]
