# Generated by Django 5.2.13 on 2026-04-18 22:10

from django.conf import settings
from django.db import migrations, models


def seed_managed_projects(apps, schema_editor):
    ManagedProject = apps.get_model('eht', 'ManagedProject')
    ProjectData = apps.get_model('eht', 'ProjectData')
    HeatTracingInput = apps.get_model('eht', 'HeatTracingInput')

    project_ids = {
        proj_id.strip()
        for proj_id in ProjectData.objects.values_list('proj_id', flat=True)
        if proj_id and proj_id.strip()
    }
    project_ids.update(
        proj_id.strip()
        for proj_id in HeatTracingInput.objects.values_list('proj_id', flat=True)
        if proj_id and proj_id.strip()
    )

    for proj_id in sorted(project_ids):
        ManagedProject.objects.get_or_create(
            proj_id=proj_id,
            defaults={'description': '', 'is_active': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0003_alter_projectdata_isolator_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_id', models.CharField(max_length=20, unique=True, verbose_name='Project ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='eht_managed_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['proj_id'],
            },
        ),
        migrations.RunPython(seed_managed_projects, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='projectdata',
            name='tracer_family',
        ),
    ]
