# Generated by Django 4.2.16 on 2025-02-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0004_eleceht_asmeb36_eleceht_calculatedtable_eleceht_io_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleceht_io',
            name='Remarks',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eleceht_io',
            name='Total_Tracer_Length',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='eleceht_io',
            name='Tracer_Length',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='max_cb_size',
            field=models.IntegerField(choices=[(10, 10), (16, 16), (20, 20), (25, 25), (32, 32), (40, 40)], default=5),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='spiral_wrap_allowed',
            field=models.CharField(choices=[(True, 'Allowed'), (False, 'Not Allowed')], default='No', max_length=30),
        ),
    ]
