# Generated by Codex on 2026-04-19

from django.db import migrations


def sync_isolator_flags(apps, schema_editor):
    ProjectData = apps.get_model('eht', 'ProjectData')

    for project in ProjectData.objects.all():
        expected_requirement = 'not_required' if project.isolator_location == 'noIsolator' else 'required'
        if project.req_local_isolator != expected_requirement:
            project.req_local_isolator = expected_requirement
            project.save(update_fields=['req_local_isolator'])


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0004_remove_projectdata_tracer_family_managedproject'),
    ]

    operations = [
        migrations.RunPython(sync_isolator_flags, migrations.RunPython.noop),
    ]
