# Generated by Django 4.2.16 on 2025-02-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0005_alter_eleceht_io_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdata',
            name='spiral_wrap_allowed',
            field=models.BooleanField(choices=[(True, 'Allowed'), (False, 'Not Allowed')], default=True),
        ),
    ]
