# Generated by Django 5.2.13 on 2026-04-19 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0005_sync_isolator_flags_and_seed_default_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLDNodeLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_id', models.CharField(max_length=255)),
                ('component_uid', models.CharField(blank=True, default='', max_length=32)),
                ('display_tag', models.CharField(blank=True, default='', max_length=100)),
                ('component_type', models.CharField(max_length=50)),
                ('line_id', models.CharField(blank=True, default='', max_length=100)),
                ('line_uid', models.CharField(blank=True, default='', max_length=100)),
                ('branch_index', models.PositiveIntegerField(default=0)),
                ('circuit_index', models.PositiveIntegerField(blank=True, null=True)),
                ('x_position', models.FloatField()),
                ('y_position', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='sld_node_layouts', to='eht.projectdata', to_field='proj_id')),
            ],
            options={
                'ordering': ['project', 'line_id', 'branch_index', 'component_type', 'display_tag'],
                'indexes': [models.Index(fields=['project', 'line_id'], name='eht_sldnode_project_23037f_idx'), models.Index(fields=['project', 'branch_index'], name='eht_sldnode_project_57dcaa_idx'), models.Index(fields=['component_uid'], name='eht_sldnode_compone_9f522c_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'component_id'), name='unique_sld_layout_component_per_project')],
            },
        ),
    ]
