# Generated by Django 4.2.16 on 2025-02-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0006_alter_projectdata_spiral_wrap_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdata',
            name='isolator_location',
            field=models.CharField(choices=[('bothSides', 'Both Sides'), ('outgoingOnly', 'Outgoing Only'), ('incomingOnly', 'Incoming Only'), ('noIsolator', 'No Isolator')], default='II', max_length=20),
        ),
    ]
