# Generated by Django 5.2.13 on 2026-04-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0006_sldnodelayout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerdistributionbranch',
            name='tagged_components',
            field=models.JSONField(default=dict),
        ),
    ]
