# Generated by Django 5.2.13 on 2026-04-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0007_alter_powerdistributionbranch_tagged_components'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='heattracinginput',
            index=models.Index(fields=['proj_id'], name='eht_heattra_proj_id_fd3133_idx'),
        ),
        migrations.AddIndex(
            model_name='heattracinginput',
            index=models.Index(fields=['proj_id', 'status'], name='eht_heattra_proj_id_00ca62_idx'),
        ),
    ]
