# Generated by Django 4.2.16 on 2025-02-21 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0007_alter_projectdata_isolator_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternateTracer',
            fields=[
                ('v_uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('a_coeff', models.FloatField()),
                ('b_coeff', models.FloatField()),
                ('c_coeff', models.FloatField()),
                ('power_at_startup_t', models.FloatField()),
                ('ohm_per_km', models.FloatField()),
                ('res_corrFactor_mica', models.FloatField()),
                ('tracer_family', models.CharField(max_length=50)),
                ('voltage_float', models.FloatField()),
                ('voltage_correction_factor', models.FloatField()),
                ('power_output', models.FloatField()),
                ('spiral_factor', models.FloatField()),
                ('tracer_length', models.FloatField()),
                ('tracer_with_margin', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BOQ',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('item_description', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HeatLoss',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('heat_loss', models.FloatField()),
                ('tracer_adder', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PowerDistribution',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('total_circuits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PowerDistributionBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_type', models.CharField(max_length=50)),
                ('circuit_count', models.IntegerField()),
                ('connected_to', models.CharField(max_length=100)),
                ('cable_length_db_to_jb', models.FloatField()),
                ('cable_length_jb_to_jb', models.FloatField()),
                ('tagged_components', models.TextField()),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='eht.powerdistribution')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessLineCalculation',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('line_size', models.FloatField()),
                ('line_length', models.FloatField()),
                ('operating_temp', models.FloatField()),
                ('heat_loss', models.FloatField()),
                ('selected_tracer', models.CharField(max_length=100)),
                ('starting_current', models.FloatField()),
                ('operating_current', models.FloatField()),
                ('total_power_consumption', models.FloatField()),
                ('spiral_factor', models.FloatField()),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedTracer',
            fields=[
                ('v_uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('a_coeff', models.FloatField()),
                ('b_coeff', models.FloatField()),
                ('c_coeff', models.FloatField()),
                ('power_at_startup_t', models.FloatField()),
                ('ohm_per_km', models.FloatField()),
                ('res_corrFactor_mica', models.FloatField()),
                ('tracer_family', models.CharField(max_length=50)),
                ('voltage_float', models.FloatField()),
                ('voltage_correction_factor', models.FloatField()),
                ('power_output', models.FloatField()),
                ('spiral_factor', models.FloatField()),
                ('tracer_length', models.FloatField()),
                ('tracer_with_margin', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='ElecEHT_CalculatedTable',
        ),
        migrations.DeleteModel(
            name='ElecEHT_IO',
        ),
    ]
