# Generated by Django 5.2.13 on 2026-04-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0008_heattracinginput_eht_heattra_proj_id_fd3133_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdata',
            name='max_cb_size',
            field=models.IntegerField(choices=[(4, 4), (6, 6), (10, 10), (16, 16), (20, 20), (25, 25), (32, 32), (40, 40)], default=10),
        ),
    ]
