# Generated by Django 5.2.13 on 2026-04-26 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0009_alter_projectdata_max_cb_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SLDTopologyEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_type', models.CharField(choices=[('combine_feeders', 'Combine Feeders'), ('split_circuits', 'Split Circuits')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('applied', 'Applied'), ('superseded', 'Superseded'), ('reset', 'Reset'), ('needs_review', 'Needs Review')], default='draft', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('baseline_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('generated_snapshot', models.JSONField(blank=True, default=dict)),
                ('edit_payload', models.JSONField(blank=True, default=dict)),
                ('validation_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sld_topology_edits', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='sld_topology_edits', to='eht.projectdata', to_field='proj_id')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['project', 'status'], name='eht_sldtopo_project_84a0ca_idx'), models.Index(fields=['project', 'edit_type'], name='eht_sldtopo_project_019a0b_idx'), models.Index(fields=['baseline_fingerprint'], name='eht_sldtopo_baselin_59d8bd_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'applied')), fields=('project',), name='unique_active_sld_topology_edit_per_project')],
            },
        ),
    ]
