# Generated by Django 5.2.13 on 2026-05-03 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0010_sldtopologyedit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CableScheduleOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_id', models.CharField(max_length=255)),
                ('component_uid', models.CharField(blank=True, default='', max_length=32)),
                ('display_tag', models.CharField(max_length=100)),
                ('component_type', models.CharField(max_length=50)),
                ('line_id', models.CharField(blank=True, default='', max_length=100)),
                ('line_uid', models.CharField(blank=True, default='', max_length=100)),
                ('branch_index', models.PositiveIntegerField(default=0)),
                ('circuit_index', models.PositiveIntegerField(blank=True, null=True)),
                ('generated_length_m', models.FloatField(blank=True, null=True)),
                ('manual_length_m', models.FloatField(blank=True, null=True)),
                ('generated_cable_size', models.CharField(blank=True, default='', max_length=50)),
                ('manual_cable_size', models.CharField(blank=True, default='', max_length=50)),
                ('remarks', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cable_overrides', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='cable_schedule_overrides', to='eht.projectdata', to_field='proj_id')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cable_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project', 'line_id', 'branch_index', 'display_tag'],
                'indexes': [models.Index(fields=['project', 'line_id'], name='eht_cablesc_project_e28198_idx'), models.Index(fields=['component_uid'], name='eht_cablesc_compone_886cd5_idx'), models.Index(fields=['display_tag'], name='eht_cablesc_display_c1c517_idx'), models.Index(fields=['is_active'], name='eht_cablesc_is_acti_737cdd_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'component_id'), name='unique_cable_override_component_per_project')],
            },
        ),
    ]
