# Generated by Django 5.2.13 on 2026-05-05 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0015_add_2a_breaker_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TracerSelectionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_v_uid', models.CharField(max_length=100)),
                ('selected_option_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tracer_overrides', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracer_selection_overrides', to='eht.heattracinginput')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='tracer_selection_overrides', to='eht.projectdata', to_field='proj_id')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tracer_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project', 'line__line_id'],
                'indexes': [models.Index(fields=['project', 'line'], name='eht_tracers_project_1d84eb_idx'), models.Index(fields=['selected_v_uid'], name='eht_tracers_selecte_e30aad_idx'), models.Index(fields=['is_active'], name='eht_tracers_is_acti_9d4698_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'line'), name='unique_tracer_override_line_per_project')],
            },
        ),
    ]
