# Generated by Django 5.2.13 on 2026-05-06 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0016_tracerselectionoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='MIAlloyTempFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alloy_type', models.CharField(max_length=50)),
                ('temperature_c', models.FloatField()),
                ('resistance_multiplier', models.FloatField()),
            ],
            options={
                'ordering': ['alloy_type', 'temperature_c'],
                'unique_together': {('alloy_type', 'temperature_c')},
            },
        ),
        migrations.CreateModel(
            name='MICableFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(choices=[('THR', 'Thermon'), ('CHR', 'Chromalox'), ('nVN', 'nVent'), ('SST', 'SST'), ('KRZ', 'KRUS-Zapad')], max_length=30)),
                ('family_name', models.CharField(max_length=50)),
                ('alloy_type', models.CharField(max_length=50)),
                ('max_voltage', models.FloatField(default=600.0)),
                ('max_sheath_temp_c', models.FloatField()),
                ('max_maintain_temp_c', models.FloatField()),
                ('max_watt_density_w_m', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'MI Cable Families',
                'unique_together': {('vendor', 'family_name')},
            },
        ),
        migrations.CreateModel(
            name='MICableHeater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100, unique=True)),
                ('conductors', models.IntegerField(default=1)),
                ('base_resistance_ohms_km', models.FloatField()),
                ('max_ampacity', models.FloatField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heaters', to='eht.micablefamily')),
            ],
            options={
                'ordering': ['base_resistance_ohms_km'],
            },
        ),
    ]
