# Generated by Codex on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0017_mialloytempfactor_micablefamily_micableheater'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatloss',
            name='base_heat_loss',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='heatloss',
            name='design_heat_loss',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='heatloss',
            name='heat_loss_sf',
            field=models.FloatField(default=1),
        ),
    ]
