# Generated by Codex on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0018_heatloss_design_basis_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatloss',
            name='accessory_adders',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='heatloss',
            name='conductivity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='heatloss',
            name='pipe_size_mm',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='heatloss',
            name='wind_correction',
            field=models.FloatField(default=1),
        ),
    ]
