# Generated by Django 5.2.13 on 2026-05-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0019_heatloss_evidence_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatloss',
            name='conductivity_basis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='heat_loss_method',
            field=models.CharField(choices=[('mean_temperature', 'Mean insulation temperature (recommended)'), ('legacy_maint_temperature', 'Legacy maintain temperature'), ('standard_table', 'Standard/vendor table (placeholder)'), ('integrated_kT', 'Integrated k(T) (placeholder)'), ('fixed_project_basis', 'Fixed project basis (placeholder)')], default='mean_temperature', max_length=40),
        ),
    ]
