# Generated by Django 5.2.13 on 2026-05-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0020_heatloss_conductivity_basis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatloss',
            name='selection_rejection_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='heatloss',
            name='selection_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
