# Generated by Django 5.2.13 on 2026-05-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0025_remove_projectdata_heating_cable_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='micableheater',
            name='tcr_per_degree_c',
            field=models.FloatField(default=0.0),
        ),
    ]
