# Generated by Django 5.2.13 on 2026-05-28 18:00

from django.db import migrations, models


def reset_sr_spiral_default(apps, schema_editor):
    ProjectData = apps.get_model('eht', 'ProjectData')
    ProjectData.objects.all().update(spiral_factor=1)


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0026_micableheater_tcr_per_degree_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternatetracer',
            name='sr_constructability_warning',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='alternatetracer',
            name='sr_parallel_run_basis',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='alternatetracer',
            name='sr_parallel_run_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='alternatetracer',
            name='sr_per_run_tracer_length',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='processlinecalculation',
            name='sr_constructability_warning',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='processlinecalculation',
            name='sr_parallel_run_basis',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='processlinecalculation',
            name='sr_parallel_run_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='sr_max_parallel_runs',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='sr_parallel_run_basis',
            field=models.CharField(choices=[('PIPE_SIZE_GUIDED', 'Pipe-size guided'), ('FIXED_PROJECT_MAXIMUM', 'Fixed project maximum')], default='PIPE_SIZE_GUIDED', max_length=30),
        ),
        migrations.AddField(
            model_name='selectedtracer',
            name='sr_constructability_warning',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='selectedtracer',
            name='sr_parallel_run_basis',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='selectedtracer',
            name='sr_parallel_run_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='selectedtracer',
            name='sr_per_run_tracer_length',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='spiral_factor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.RunPython(reset_sr_spiral_default, migrations.RunPython.noop),
    ]
