# Generated by Django 5.2.13 on 2026-05-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0027_alternatetracer_sr_constructability_warning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micableheater',
            name='tcr_per_degree_c',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
