# Generated by Codex on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0028_alter_micableheater_tcr_per_degree_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdata',
            name='cable_conductor_material',
            field=models.CharField(choices=[('Cu', 'Copper'), ('Al', 'Aluminium')], default='Cu', max_length=5),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='cable_grouping_derating',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='cable_install_method',
            field=models.CharField(choices=[('E', 'E - Multi-core on open cable tray or ladder'), ('B2', 'B2 - Multi-core in conduit in wall or enclosure'), ('C', 'C - Clipped direct to surface'), ('D1', 'D1 - In duct in ground, single cable'), ('D2', 'D2 - Direct buried in ground')], default='E', max_length=5),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='cable_insulation_type',
            field=models.CharField(choices=[('XLPE', 'XLPE'), ('PVC', 'PVC')], default='XLPE', max_length=10),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='cable_standard',
            field=models.CharField(choices=[('IEC_60502_1', 'IEC 60502-1 (international)'), ('BS_5467', 'BS 5467 (UK)')], default='IEC_60502_1', max_length=20),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='gfep_provided',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='mcb_curve',
            field=models.CharField(choices=[('B', 'Type B (3-5x In)'), ('C', 'Type C (5-10x In)'), ('D', 'Type D (10-20x In)')], default='C', max_length=5),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='min_cold_cable_size_mm2',
            field=models.CharField(choices=[('CALCULATED', 'Calculated (no minimum)'), ('2.5', '2.5 mm²'), ('4', '4 mm²'), ('6', '6 mm²'), ('10', '10 mm²')], default='CALCULATED', max_length=15),
        ),
        migrations.CreateModel(
            name='ColdCableCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(blank=True, default='', max_length=60)),
                ('cable_standard', models.CharField(choices=[('IEC_60502_1', 'IEC 60502-1 (international)'), ('BS_5467', 'BS 5467 (UK)')], max_length=20)),
                ('catalogue_ref', models.CharField(blank=True, default='', max_length=100)),
                ('cable_type_code', models.CharField(max_length=50)),
                ('voltage_grade', models.CharField(default='0.6/1kV', max_length=20)),
                ('conductor_material', models.CharField(choices=[('Cu', 'Copper'), ('Al', 'Aluminium')], max_length=5)),
                ('insulation_type', models.CharField(choices=[('XLPE', 'XLPE'), ('PVC', 'PVC')], max_length=10)),
                ('core_count', models.IntegerField(choices=[(2, '2C'), (3, '3C'), (4, '4C')])),
                ('conductor_size_mm2', models.FloatField()),
                ('installation_method', models.CharField(choices=[('E', 'E - Multi-core on open cable tray or ladder'), ('B2', 'B2 - Multi-core in conduit in wall or enclosure'), ('C', 'C - Clipped direct to surface'), ('D1', 'D1 - In duct in ground, single cable'), ('D2', 'D2 - Direct buried in ground')], max_length=5)),
                ('ampacity_a', models.FloatField()),
                ('ampacity_temp_ref_c', models.FloatField(default=30.0)),
                ('max_conductor_temp_c', models.FloatField(default=90.0)),
                ('resistance_mohm_per_m', models.FloatField()),
                ('reactance_mohm_per_m', models.FloatField(default=0.08)),
                ('source_document', models.CharField(blank=True, default='', max_length=200)),
                ('source_date', models.DateField(blank=True, null=True)),
                ('is_validated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['conductor_material', 'insulation_type', 'core_count', 'conductor_size_mm2'],
                'indexes': [models.Index(fields=['conductor_material', 'insulation_type', 'core_count', 'installation_method'], name='eht_coldcab_conduct_3f41e6_idx'), models.Index(fields=['is_validated'], name='eht_coldcab_is_vali_403049_idx')],
                'constraints': [models.UniqueConstraint(fields=('cable_standard', 'conductor_material', 'insulation_type', 'core_count', 'conductor_size_mm2', 'installation_method'), name='unique_cold_cable_catalogue_row')],
            },
        ),
    ]
