# Generated by Django 5.2.13 on 2026-05-29 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0029_cold_cable_foundation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coldcablecatalogue',
            name='installation_method',
            field=models.CharField(choices=[('E', 'E - Multi-core on open cable tray or ladder'), ('B2', 'B2 - Multi-core in conduit in wall or enclosure'), ('C', 'C - Clipped direct to surface'), ('D1', 'D1 - In duct in ground, single cable'), ('D2', 'D2 - Direct buried in ground')], max_length=5),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='cable_install_method',
            field=models.CharField(choices=[('E', 'E - Multi-core on open cable tray or ladder'), ('B2', 'B2 - Multi-core in conduit in wall or enclosure'), ('C', 'C - Clipped direct to surface'), ('D1', 'D1 - In duct in ground, single cable'), ('D2', 'D2 - Direct buried in ground')], default='E', max_length=5),
        ),
        migrations.CreateModel(
            name='ColdCableResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_index', models.PositiveIntegerField()),
                ('line_id', models.CharField(max_length=100)),
                ('line_uid', models.CharField(max_length=100)),
                ('heating_cable_type', models.CharField(default='SR', max_length=10)),
                ('per_circuit_operating_current_a', models.FloatField(default=0.0)),
                ('line_operating_current_a', models.FloatField(default=0.0)),
                ('breaker_size_a', models.FloatField(default=0.0)),
                ('circuit_count', models.IntegerField(default=0)),
                ('mcb_curve', models.CharField(choices=[('B', 'Type B (3-5x In)'), ('C', 'Type C (5-10x In)'), ('D', 'Type D (10-20x In)')], default='C', max_length=5)),
                ('gfep_provided', models.BooleanField(default=True)),
                ('length_4c_m', models.FloatField(blank=True, null=True)),
                ('length_3c_m', models.FloatField(blank=True, null=True)),
                ('length_basis', models.CharField(default='project_default', max_length=30)),
                ('site_ambient_temp_c', models.FloatField(default=0.0)),
                ('catalogue_temp_ref_c', models.FloatField(default=30.0)),
                ('k_temp', models.FloatField(blank=True, null=True)),
                ('k_group', models.FloatField(default=1.0)),
                ('k_total', models.FloatField(blank=True, null=True)),
                ('install_method', models.CharField(choices=[('E', 'E - Multi-core on open cable tray or ladder'), ('B2', 'B2 - Multi-core in conduit in wall or enclosure'), ('C', 'C - Clipped direct to surface'), ('D1', 'D1 - In duct in ground, single cable'), ('D2', 'D2 - Direct buried in ground')], default='E', max_length=5)),
                ('cable_4c_size_mm2', models.FloatField(blank=True, null=True)),
                ('cable_4c_ampacity_derated_a', models.FloatField(blank=True, null=True)),
                ('cable_4c_ampacity_margin_pct', models.FloatField(blank=True, null=True)),
                ('cable_4c_vd_v', models.FloatField(blank=True, null=True)),
                ('cable_4c_vd_pct', models.FloatField(blank=True, null=True)),
                ('cable_3c_size_mm2', models.FloatField(blank=True, null=True)),
                ('cable_3c_ampacity_derated_a', models.FloatField(blank=True, null=True)),
                ('cable_3c_ampacity_margin_pct', models.FloatField(blank=True, null=True)),
                ('cable_3c_vd_v', models.FloatField(blank=True, null=True)),
                ('cable_3c_vd_pct', models.FloatField(blank=True, null=True)),
                ('vd_total_pct', models.FloatField(blank=True, null=True)),
                ('vd_allowable_pct', models.FloatField(default=0.0)),
                ('vd_status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('review_required', 'Review Required'), ('not_calculated', 'Not Calculated')], default='not_calculated', max_length=20)),
                ('load_end_voltage_v', models.FloatField(blank=True, null=True)),
                ('optimization_run', models.BooleanField(default=False)),
                ('conductor_volume_proxy', models.FloatField(blank=True, null=True)),
                ('fault_current_4c_phase_to_phase_a', models.FloatField(blank=True, null=True)),
                ('fault_protection_4c_status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('review_required', 'Review Required'), ('not_calculated', 'Not Calculated')], default='not_calculated', max_length=20)),
                ('fault_current_3c_line_to_neutral_a', models.FloatField(blank=True, null=True)),
                ('fault_protection_3c_status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('review_required', 'Review Required'), ('not_calculated', 'Not Calculated')], default='not_calculated', max_length=20)),
                ('sizing_status', models.CharField(choices=[('selected', 'Selected'), ('review_required', 'Review Required'), ('unsizeable', 'Unsizeable - no feasible cable found'), ('length_missing', 'Length Basis Missing')], max_length=20)),
                ('review_notes', models.JSONField(blank=True, default=list)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cold_cable_results', to='eht.powerdistributionbranch')),
                ('cable_3c_catalogue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_3c', to='eht.coldcablecatalogue')),
                ('cable_4c_catalogue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_4c', to='eht.coldcablecatalogue')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cold_cable_results', to='eht.powerdistribution')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='cold_cable_results', to='eht.projectdata', to_field='proj_id')),
            ],
            options={
                'ordering': ['project', 'line_id', 'branch_index'],
                'indexes': [models.Index(fields=['project', 'sizing_status'], name='eht_coldcab_project_cf25aa_idx'), models.Index(fields=['line_id', 'branch_index'], name='eht_coldcab_line_id_50c3d9_idx')],
                'constraints': [models.UniqueConstraint(fields=('distribution', 'branch_index'), name='unique_cold_cable_result_per_branch')],
            },
        ),
    ]
