# Generated by Django 5.2.13 on 2026-05-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0030_cold_cable_ampacity_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldcableresult',
            name='cable_3c_conductor_temp_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coldcableresult',
            name='cable_4c_conductor_temp_c',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
