# Generated by Django 5.2.13 on 2026-05-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0031_coldcableresult_cable_3c_conductor_temp_c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldcableresult',
            name='cable_3c_conductor_mass_mt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coldcableresult',
            name='cable_4c_conductor_mass_mt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coldcableresult',
            name='conductor_mass_total_mt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coldcableresult',
            name='conductor_material_density_kg_m3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
