# Generated by Django 5.2.13 on 2026-05-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0032_coldcableresult_cable_3c_conductor_mass_mt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldcableresult',
            name='cable_3c_segments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
