# Generated by Django 5.2.13 on 2026-06-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0037_remove_legacy_3c_fault_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cablescheduleoverride',
            name='cable_lot',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='cablescheduleoverride',
            name='checked_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cablescheduleoverride',
            name='checked_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cablescheduleoverride',
            name='drum_tag',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='cablescheduleoverride',
            name='installation_area',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='cablescheduleoverride',
            name='installation_basis',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='cablescheduleoverride',
            name='review_status',
            field=models.CharField(choices=[('generated', 'Generated'), ('review_required', 'Review required'), ('checked', 'Checked'), ('issued', 'Issued')], default='generated', max_length=30),
        ),
        migrations.AddField(
            model_name='cablescheduleoverride',
            name='route_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='cablescheduleoverride',
            name='schedule_revision',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
    ]
