# Generated by Django 5.2.13 on 2026-06-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0038_cablescheduleoverride_cable_lot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldcableresult',
            name='per_circuit_starting_current_a',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coldcableresult',
            name='startup_vd_basis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='coldcableresult',
            name='startup_vd_status',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('review_required', 'Review Required'), ('not_calculated', 'Not Calculated')], default='not_calculated', max_length=20),
        ),
        migrations.AddField(
            model_name='coldcableresult',
            name='startup_vd_threshold_pct',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='coldcableresult',
            name='startup_vd_total_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='startup_vd_warning_threshold_pct',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
    ]
