# Generated by Django 5.2.13 on 2026-06-14 23:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0039_coldcableresult_per_circuit_starting_current_a_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorFileRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default upload error-file retention', max_length=80)),
                ('max_error_files', models.PositiveSmallIntegerField(default=10, help_text='Maximum number of upload validation error workbooks retained on the server.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('max_file_size_mb', models.DecimalField(decimal_places=2, default=5, help_text='Maximum size of each retained error workbook. Default 5 MB; total retained size is bounded by file count times this value.', max_digits=6, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Error file retention policy',
                'verbose_name_plural': 'Error file retention policy',
            },
        ),
    ]
