# Generated by Codex on 2026-06-15

from django.db import migrations, models
import django.db.models.deletion


def validate_heat_tracing_input_project_ids(apps, schema_editor):
    HeatTracingInput = apps.get_model('eht', 'HeatTracingInput')
    ProjectData = apps.get_model('eht', 'ProjectData')

    valid_project_ids = set(
        ProjectData.objects.exclude(proj_id__isnull=True)
        .exclude(proj_id='')
        .values_list('proj_id', flat=True)
    )

    invalid_values = []
    for value in (
        HeatTracingInput.objects.exclude(proj_id__isnull=True)
        .values_list('proj_id', flat=True)
        .distinct()
    ):
        if not value or len(value) > 20 or value not in valid_project_ids:
            invalid_values.append(value)

    if invalid_values:
        sample = ', '.join(repr(value) for value in invalid_values[:10])
        raise RuntimeError(
            'Cannot add HeatTracingInput -> ProjectData foreign key. '
            'Line-list rows reference missing, blank, or overlength project IDs: '
            f'{sample}. Create the matching ProjectData row or remove/remap those '
            'project-owned line-list rows before applying this migration. '
            'No catalogue/reference data has been changed.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0040_errorfileretentionpolicy'),
    ]

    operations = [
        migrations.RunPython(
            validate_heat_tracing_input_project_ids,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='heattracinginput',
                    name='proj_id',
                    field=models.CharField(blank=True, db_column='proj_id', max_length=50, null=True),
                ),
                migrations.RenameField(
                    model_name='heattracinginput',
                    old_name='proj_id',
                    new_name='proj',
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='heattracinginput',
            name='proj',
            field=models.ForeignKey(
                blank=True,
                db_column='proj_id',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='input_lines',
                to='eht.projectdata',
                to_field='proj_id',
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='heattracinginput',
                    name='eht_heattra_proj_id_fd3133_idx',
                ),
                migrations.RemoveIndex(
                    model_name='heattracinginput',
                    name='eht_heattra_proj_id_00ca62_idx',
                ),
                migrations.AddIndex(
                    model_name='heattracinginput',
                    index=models.Index(fields=['proj'], name='eht_heattra_proj_id_fd3133_idx'),
                ),
                migrations.AddIndex(
                    model_name='heattracinginput',
                    index=models.Index(fields=['proj', 'status'], name='eht_heattra_proj_id_00ca62_idx'),
                ),
            ],
            database_operations=[],
        ),
    ]
