# Generated by Django 5.2.13 on 2026-06-15 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0041_heattracinginput_project_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CableScheduleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cable_tag', models.CharField(max_length=120)),
                ('component_id', models.CharField(blank=True, default='', max_length=255)),
                ('component_type', models.CharField(blank=True, default='', max_length=50)),
                ('line_ids', models.CharField(blank=True, default='', max_length=255)),
                ('cable_specification', models.CharField(blank=True, default='', max_length=120)),
                ('calculated_cold_cable_size', models.CharField(blank=True, default='', max_length=80)),
                ('cable_length_m', models.FloatField(blank=True, null=True)),
                ('connected_from', models.CharField(blank=True, default='', max_length=255)),
                ('connected_to', models.CharField(blank=True, default='', max_length=255)),
                ('purpose', models.CharField(blank=True, default='', max_length=160)),
                ('review_status', models.CharField(choices=[('generated', 'Generated'), ('review_required', 'Review required'), ('checked', 'Checked'), ('issued', 'Issued')], default='generated', max_length=30)),
                ('schedule_signature', models.CharField(max_length=64)),
                ('internal_revision', models.PositiveIntegerField(default=0)),
                ('lifecycle_status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired')], default='active', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_cable_schedule_records', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_cable_schedule_records', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='cable_schedule_records', to='eht.projectdata', to_field='proj_id')),
                ('retired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retired_cable_schedule_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project', 'cable_tag'],
                'indexes': [models.Index(fields=['project', 'lifecycle_status'], name='eht_cablesc_project_5ac981_idx'), models.Index(fields=['project', 'internal_revision'], name='eht_cablesc_project_ff6b13_idx'), models.Index(fields=['cable_tag'], name='eht_cablesc_cable_t_2dcfe4_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'cable_tag'), name='unique_cable_schedule_record_tag_per_project')],
            },
        ),
    ]
