# Generated by Django 5.2.13 on 2026-06-15 01:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0042_cableschedulerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='processlinecalculation',
            name='calculated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
