# Generated by Django 5.2.13 on 2026-07-08 19:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RacewayFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('ladder', 'Ladder'), ('perforated_tray', 'Perforated tray'), ('solid_tray', 'Solid tray'), ('mesh_tray', 'Mesh tray'), ('trunking', 'Trunking'), ('sleeve', 'Sleeve')], max_length=40)),
                ('material', models.CharField(default='HDG steel', max_length=80)),
                ('standard_length_mm', models.PositiveIntegerField(default=3000, validators=[django.core.validators.MinValueValidator(1)])),
                ('standard_basis', models.CharField(default='IEC 61537', max_length=80)),
                ('profile', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['kind', 'is_active'], name='raceway_rac_kind_b2a827_idx'), models.Index(fields=['standard_basis'], name='raceway_rac_standar_ce70e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='RacewayLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(db_index=True, max_length=80)),
                ('source_model_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('render_package_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('revision', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raceway_layers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project_id', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RacewayRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tag', models.CharField(blank=True, default='', max_length=120)),
                ('service_class', models.CharField(choices=[('power', 'Power'), ('control', 'Control'), ('instrument', 'Instrument'), ('telecom', 'Telecom'), ('other', 'Other')], default='power', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('committed', 'Committed'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('coordinate_frame', models.CharField(default='source_xyz_m', max_length=40)),
                ('elevation_m', models.FloatField(blank=True, null=True)),
                ('source_model_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('render_package_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('validation_summary', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='raceway.racewayfamily')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='raceway.racewaylayer')),
            ],
            options={
                'ordering': ['layer', 'tag', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RacewayNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sequence', models.PositiveIntegerField()),
                ('node_kind', models.CharField(choices=[('endpoint', 'Endpoint'), ('bend', 'Bend'), ('branch', 'Branch'), ('riser', 'Riser'), ('intermediate', 'Intermediate')], default='intermediate', max_length=30)),
                ('source_x_m', models.FloatField()),
                ('source_y_m', models.FloatField()),
                ('source_z_m', models.FloatField()),
                ('anchor', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='raceway.racewayrun')),
            ],
            options={
                'ordering': ['run', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RacewaySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_mm', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('depth_mm', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('weight_kg_per_m', models.FloatField(blank=True, null=True)),
                ('load_span_table', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sizes', to='raceway.racewayfamily')),
            ],
            options={
                'ordering': ['family__code', 'width_mm', 'depth_mm'],
            },
        ),
        migrations.AddField(
            model_name='racewayrun',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='raceway.racewaysize'),
        ),
        migrations.AddIndex(
            model_name='racewaylayer',
            index=models.Index(fields=['project_id', 'status'], name='raceway_rac_project_fd945c_idx'),
        ),
        migrations.AddIndex(
            model_name='racewaylayer',
            index=models.Index(fields=['project_id', 'source_model_id'], name='raceway_rac_project_4d3d49_idx'),
        ),
        migrations.AddIndex(
            model_name='racewaylayer',
            index=models.Index(fields=['project_id', 'render_package_id'], name='raceway_rac_project_54baff_idx'),
        ),
        migrations.AddIndex(
            model_name='racewaynode',
            index=models.Index(fields=['run', 'sequence'], name='raceway_rac_run_id_c3763d_idx'),
        ),
        migrations.AddConstraint(
            model_name='racewaynode',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='raceway_unique_node_sequence_per_run'),
        ),
        migrations.AddIndex(
            model_name='racewaysize',
            index=models.Index(fields=['family', 'is_active'], name='raceway_rac_family__1fa2f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='racewaysize',
            constraint=models.UniqueConstraint(fields=('family', 'width_mm', 'depth_mm'), name='raceway_unique_size_per_family'),
        ),
        migrations.AddIndex(
            model_name='racewayrun',
            index=models.Index(fields=['layer', 'status'], name='raceway_rac_layer_i_12b1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='racewayrun',
            index=models.Index(fields=['service_class'], name='raceway_rac_service_47c7db_idx'),
        ),
        migrations.AddIndex(
            model_name='racewayrun',
            index=models.Index(fields=['source_model_id', 'render_package_id'], name='raceway_rac_source__2ad688_idx'),
        ),
    ]
