# Generated by Django 5.2.13 on 2026-07-12 09:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.CharField(db_index=True, max_length=80)),
                ('owner_module', models.CharField(max_length=40)),
                ('suggestion_code', models.CharField(db_index=True, max_length=120)),
                ('action', models.CharField(choices=[('shown', 'Shown'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('edited', 'Edited'), ('dismissed', 'Dismissed'), ('unresolved_at_save', 'Unresolved at save')], max_length=30)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('action_detail', models.JSONField(blank=True, default=dict)),
                ('client', models.CharField(blank=True, default='', max_length=80)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestion_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['project_id', 'suggestion_code'], name='telemetry_s_project_76e7d0_idx'), models.Index(fields=['suggestion_code', 'action'], name='telemetry_s_suggest_e6b074_idx'), models.Index(fields=['created_at'], name='telemetry_s_created_44dacc_idx')],
            },
        ),
    ]
