# Generated by Django 5.2.13 on 2026-08-28 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestionevent',
            name='session_key',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='suggestionevent',
            index=models.Index(fields=['project_id', 'session_key'], name='telemetry_s_project_5e74d8_idx'),
        ),
    ]
