# Generated by Django 5.2.13 on 2026-06-21 22:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eht', '0043_processlinecalculation_calculated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('render_package', 'Render Package'), ('metadata_index', 'Metadata Index')], default='render_package', max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tool_name', models.CharField(blank=True, default='', max_length=80)),
                ('tool_version', models.CharField(blank=True, default='', max_length=80)),
                ('input_storage_key', models.CharField(blank=True, default='', max_length=500)),
                ('output_storage_prefix', models.CharField(blank=True, default='', max_length=500)),
                ('log', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RenderPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_format', models.CharField(choices=[('GLB', 'GLB'), ('GLTF', 'glTF'), ('TILED_JSON', 'Tiled JSON Manifest'), ('CUSTOM', 'Custom')], max_length=30)),
                ('storage_prefix', models.CharField(max_length=500)),
                ('manifest_storage_key', models.CharField(blank=True, default='', max_length=500)),
                ('object_count', models.PositiveIntegerField(default=0)),
                ('tile_count', models.PositiveIntegerField(default=0)),
                ('byte_size', models.BigIntegerField(default=0)),
                ('coordinate_unit', models.CharField(blank=True, default='', max_length=30)),
                ('coordinate_frame', models.CharField(blank=True, default='', max_length=80)),
                ('bounds', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversion_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='render_packages', to='plant3d.conversionjob')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RenderTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile_id', models.CharField(max_length=120)),
                ('storage_key', models.CharField(max_length=500)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('rtc_origin_x', models.FloatField(default=0.0)),
                ('rtc_origin_y', models.FloatField(default=0.0)),
                ('rtc_origin_z', models.FloatField(default=0.0)),
                ('bounds', models.JSONField(blank=True, default=dict)),
                ('object_count', models.PositiveIntegerField(default=0)),
                ('byte_size', models.BigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('render_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='plant3d.renderpackage')),
            ],
            options={
                'ordering': ['render_package', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SourceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('source_format', models.CharField(choices=[('IFC', 'IFC'), ('IDF', 'IDF'), ('PCF', 'PCF'), ('OTHER', 'Other')], max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=500)),
                ('content_signature', models.CharField(blank=True, default='', max_length=64)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('source_system', models.CharField(blank=True, default='', max_length=80)),
                ('declared_unit', models.CharField(blank=True, default='', max_length=30)),
                ('coordinate_frame', models.CharField(blank=True, default='', max_length=80)),
                ('bounds', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='plant3d_source_models', to='eht.projectdata', to_field='proj_id')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='renderpackage',
            name='source_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='render_packages', to='plant3d.sourcemodel'),
        ),
        migrations.CreateModel(
            name='ModelObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(max_length=160)),
                ('source_object_id', models.CharField(blank=True, default='', max_length=160)),
                ('object_type', models.CharField(blank=True, default='', max_length=80)),
                ('tag', models.CharField(blank=True, default='', max_length=160)),
                ('line_id', models.CharField(blank=True, default='', max_length=160)),
                ('bounds', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('render_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_objects', to='plant3d.renderpackage')),
                ('render_tile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_objects', to='plant3d.rendertile')),
                ('source_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_objects', to='plant3d.sourcemodel')),
            ],
            options={
                'ordering': ['source_model', 'stable_id'],
            },
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='source_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_jobs', to='plant3d.sourcemodel'),
        ),
        migrations.AddIndex(
            model_name='rendertile',
            index=models.Index(fields=['render_package', 'sequence'], name='plant3d_ren_render__eadf70_idx'),
        ),
        migrations.AddConstraint(
            model_name='rendertile',
            constraint=models.UniqueConstraint(fields=('render_package', 'tile_id'), name='plant3d_unique_tile_per_package'),
        ),
        migrations.AddIndex(
            model_name='sourcemodel',
            index=models.Index(fields=['project', 'source_format'], name='plant3d_sou_project_9e7f77_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcemodel',
            index=models.Index(fields=['project', 'content_signature'], name='plant3d_sou_project_c95ad7_idx'),
        ),
        migrations.AddIndex(
            model_name='renderpackage',
            index=models.Index(fields=['source_model', 'package_format'], name='plant3d_ren_source__0cedcc_idx'),
        ),
        migrations.AddIndex(
            model_name='renderpackage',
            index=models.Index(fields=['created_at'], name='plant3d_ren_created_643efe_idx'),
        ),
        migrations.AddIndex(
            model_name='modelobject',
            index=models.Index(fields=['source_model', 'object_type'], name='plant3d_mod_source__3041b6_idx'),
        ),
        migrations.AddIndex(
            model_name='modelobject',
            index=models.Index(fields=['source_model', 'tag'], name='plant3d_mod_source__ce656d_idx'),
        ),
        migrations.AddIndex(
            model_name='modelobject',
            index=models.Index(fields=['source_model', 'line_id'], name='plant3d_mod_source__be9c42_idx'),
        ),
        migrations.AddConstraint(
            model_name='modelobject',
            constraint=models.UniqueConstraint(fields=('source_model', 'stable_id'), name='plant3d_unique_object_per_source'),
        ),
        migrations.AddIndex(
            model_name='conversionjob',
            index=models.Index(fields=['source_model', 'status'], name='plant3d_con_source__181c16_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionjob',
            index=models.Index(fields=['status', 'created_at'], name='plant3d_con_status_59cce7_idx'),
        ),
    ]
