# Generated by Django 5.2.13 on 2026-07-01 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0043_processlinecalculation_calculated_at'),
        ('plant3d', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcemodel',
            name='is_saved_case',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sourcemodel',
            name='saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourcemodel',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plant3d_source_models', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sourcemodel',
            index=models.Index(fields=['project', 'uploaded_by', 'is_saved_case'], name='plant3d_sou_project_a2eefc_idx'),
        ),
    ]
