# Generated by Django 5.2.13 on 2026-04-20 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eht', '0007_alter_powerdistributionbranch_tagged_components'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('min_x', models.FloatField(blank=True, null=True)),
                ('max_x', models.FloatField(blank=True, null=True)),
                ('min_y', models.FloatField(blank=True, null=True)),
                ('max_y', models.FloatField(blank=True, null=True)),
                ('min_z', models.FloatField(blank=True, null=True)),
                ('max_z', models.FloatField(blank=True, null=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='idf_files', to='eht.projectdata', to_field='proj_id')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='IDFComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('record_id', models.IntegerField()),
                ('kind', models.CharField(max_length=50)),
                ('line_id', models.CharField(blank=True, default='', max_length=100)),
                ('properties', models.JSONField(default=dict)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='idf_components', to='eht.projectdata', to_field='proj_id')),
                ('idf_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='idfviewer.idffile')),
            ],
            options={
                'ordering': ['idf_file', 'uid'],
                'indexes': [models.Index(fields=['project', 'line_id'], name='idfviewer_i_project_f282d3_idx'), models.Index(fields=['kind'], name='idfviewer_i_kind_aaf2ac_idx')],
            },
        ),
    ]
