# Generated by Django 5.2.13 on 2026-04-20 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0007_alter_powerdistributionbranch_tagged_components'),
        ('idfviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotPlanOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plot_plans/')),
                ('scale', models.FloatField(default=1.0)),
                ('offset_x', models.FloatField(default=0.0)),
                ('offset_z', models.FloatField(default=0.0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='plot_plan', to='eht.projectdata', to_field='proj_id')),
            ],
        ),
    ]
