# Generated by Django 5.2.13 on 2026-04-21 20:51

import django.db.models.deletion
from django.db import migrations, models


def _infer_scene_bucket(component):
    properties = component.properties or {}
    kind = (component.kind or '').strip().lower()
    record_id = component.record_id

    if properties.get('raw_start') is not None and properties.get('raw_end') is not None:
        if record_id in {100, 101, 102, 103} or kind in {
            'pipe',
            'fixed pipe',
            'pipe block fixed',
            'pipe block variable',
        }:
            return 'pipes'
        return 'fittings'

    if record_id == 120 or kind == 'weld':
        return 'welds'
    if record_id == 150 or 'support' in kind:
        return 'supports'
    return 'markers'


def backfill_saved_file_metadata(apps, schema_editor):
    IDFFile = apps.get_model('idfviewer', 'IDFFile')
    IDFComponent = apps.get_model('idfviewer', 'IDFComponent')

    for component in IDFComponent.objects.all().only('id', 'kind', 'record_id', 'properties', 'scene_bucket'):
        scene_bucket = _infer_scene_bucket(component)
        if component.scene_bucket != scene_bucket:
            component.scene_bucket = scene_bucket
            component.save(update_fields=['scene_bucket'])

    for saved_file in IDFFile.objects.all().only(
        'id',
        'uploaded_at',
        'last_saved_at',
        'component_count',
        'pipe_count',
        'fitting_count',
        'weld_count',
        'support_count',
        'marker_count',
    ):
        counts = {
            'pipes': 0,
            'fittings': 0,
            'welds': 0,
            'supports': 0,
            'markers': 0,
        }
        for component in IDFComponent.objects.filter(idf_file=saved_file).only('scene_bucket'):
            counts[component.scene_bucket or 'fittings'] += 1

        saved_file.last_saved_at = saved_file.last_saved_at or saved_file.uploaded_at
        saved_file.component_count = sum(counts.values())
        saved_file.pipe_count = counts['pipes']
        saved_file.fitting_count = counts['fittings']
        saved_file.weld_count = counts['welds']
        saved_file.support_count = counts['supports']
        saved_file.marker_count = counts['markers']
        saved_file.save(
            update_fields=[
                'last_saved_at',
                'component_count',
                'pipe_count',
                'fitting_count',
                'weld_count',
                'support_count',
                'marker_count',
            ]
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0007_alter_powerdistributionbranch_tagged_components'),
        ('idfviewer', '0003_idffile_source_format_idfcomponent_source_format_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDFFileSaveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('replaced', 'Replaced')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_component_count', models.PositiveIntegerField(default=0)),
                ('component_count', models.PositiveIntegerField(default=0)),
                ('previous_counts', models.JSONField(default=dict)),
                ('current_counts', models.JSONField(default=dict)),
                ('previous_signature', models.CharField(blank=True, default='', max_length=64)),
                ('current_signature', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='idfcomponent',
            new_name='idfviewer_i_project_bffdb5_idx',
            old_name='idfviewer_i_project_9f4374_idx',
        ),
        migrations.AddField(
            model_name='idfcomponent',
            name='scene_bucket',
            field=models.CharField(choices=[('pipes', 'Pipes'), ('fittings', 'Fittings'), ('welds', 'Welds'), ('supports', 'Supports'), ('markers', 'Markers')], default='fittings', max_length=20),
        ),
        migrations.AddField(
            model_name='idffile',
            name='component_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='idffile',
            name='content_signature',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='idffile',
            name='fitting_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='idffile',
            name='last_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idffile',
            name='marker_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='idffile',
            name='pipe_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='idffile',
            name='support_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='idffile',
            name='weld_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='idffilesaveevent',
            name='idf_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_events', to='idfviewer.idffile'),
        ),
        migrations.AddField(
            model_name='idffilesaveevent',
            name='project',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='idf_file_save_events', to='eht.projectdata', to_field='proj_id'),
        ),
        migrations.RunPython(backfill_saved_file_metadata, noop_reverse),
    ]
