# Generated by Codex on 2026-06-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0007_alter_powerdistributionbranch_tagged_components'),
        ('idfviewer', '0004_idffilesaveevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAttributeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_format', models.CharField(choices=[('PCF', 'PCF')], default='PCF', max_length=10)),
                ('attribute_key', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=120)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='idf_attribute_mappings', to='eht.projectdata', to_field='proj_id')),
            ],
            options={
                'ordering': ['display_order', 'attribute_key'],
                'indexes': [models.Index(fields=['project', 'source_format'], name='idfviewer_p_project_a24a45_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'source_format', 'attribute_key'), name='idfviewer_unique_project_attribute_mapping')],
            },
        ),
    ]
