# Generated by Django 5.2.13 on 2026-06-20 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0043_processlinecalculation_calculated_at'),
        ('idfviewer', '0005_projectattributemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='EHTDesignElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_uid', models.CharField(max_length=64)),
                ('element_type', models.CharField(choices=[('distribution_board', 'Distribution Board'), ('junction_box', 'Junction Box'), ('isolator', 'Isolator'), ('tracer_sr', 'SR Tracer'), ('tracer_mi', 'MI Tracer'), ('rtd', 'RTD'), ('cold_cable', 'Cold Cable'), ('end_termination', 'End Termination'), ('pipe_strap', 'Pipe Strap')], max_length=40)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('geometry', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idf_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eht_design_elements', to='idfviewer.idffile')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='idf_eht_design_elements', to='eht.projectdata', to_field='proj_id')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['project', 'idf_file'], name='idfviewer_e_project_f2d548_idx'), models.Index(fields=['project', 'element_type'], name='idfviewer_e_project_199e97_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'idf_file', 'element_uid'), name='idfviewer_unique_eht_element_per_file_scope')],
            },
        ),
    ]
